import 'package:flutter/material.dart';
import 'caption_style.dart';

/// A large, varied library of caption templates — mixing every animation
/// style (highlight, pop, bounce, typewriter, slide, fade, static) with a
/// range of color themes (neon, pastel, gold, monochrome, etc), similar
/// in spirit to the large template libraries in Zeemo/CapCut. Add more
/// by appending to this list — no other code changes needed.
class CaptionTemplates {
  static const List<CaptionTemplate> all = [
    // ---------- Word-highlight / karaoke style ----------
    CaptionTemplate(
      id: 'classic_highlight',
      name: 'Classic Highlight',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Colors.yellowAccent,
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'hormozi_style',
      name: 'Creator Bold',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFF00E676),
      strokeColor: Colors.black,
      strokeWidth: 3.0,
      fontWeight: FontWeight.w900,
      fontSize: 1.25,
    ),
    CaptionTemplate(
      id: 'karaoke_pink',
      name: 'Karaoke Pink',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white70,
      highlightColor: Color(0xFFFF3B7F),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'karaoke_blue',
      name: 'Karaoke Blue',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFF29B6F6),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'karaoke_purple',
      name: 'Royal Purple',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFFAB47BC),
      strokeColor: Colors.black,
      fontWeight: FontWeight.w800,
    ),
    CaptionTemplate(
      id: 'mrbeast_style',
      name: 'MrBeast Style',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFFFFEB3B),
      strokeColor: Colors.black,
      strokeWidth: 3.5,
      fontWeight: FontWeight.w900,
      fontSize: 1.3,
    ),
    CaptionTemplate(
      id: 'mint_highlight',
      name: 'Mint Fresh',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFF64FFDA),
      strokeColor: Colors.black87,
    ),
    CaptionTemplate(
      id: 'monochrome_highlight',
      name: 'Monochrome',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white70,
      highlightColor: Colors.white,
      strokeColor: Colors.black,
      fontWeight: FontWeight.w700,
    ),
    CaptionTemplate(
      id: 'red_alert',
      name: 'Red Alert',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFFFF1744),
      strokeColor: Colors.black,
      fontWeight: FontWeight.w900,
    ),
    CaptionTemplate(
      id: 'gold_highlight',
      name: 'Gold Standard',
      animation: CaptionAnimation.wordHighlight,
      textColor: Colors.white,
      highlightColor: Color(0xFFFFD700),
      strokeColor: Colors.black,
      strokeWidth: 2.5,
    ),

    // ---------- Pop-in style ----------
    CaptionTemplate(
      id: 'bold_pop',
      name: 'Bold Pop',
      animation: CaptionAnimation.popIn,
      textColor: Colors.white,
      highlightColor: Colors.orangeAccent,
      fontWeight: FontWeight.w900,
      fontSize: 1.15,
    ),
    CaptionTemplate(
      id: 'blue_pop',
      name: 'Electric Pop',
      animation: CaptionAnimation.popIn,
      textColor: Colors.white,
      highlightColor: Color(0xFF00B4FF),
      strokeColor: Colors.black,
      fontSize: 1.1,
    ),
    CaptionTemplate(
      id: 'candy_pop',
      name: 'Candy Pop',
      animation: CaptionAnimation.popIn,
      textColor: Colors.white,
      highlightColor: Color(0xFFFF6EC7),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'lime_pop',
      name: 'Lime Pop',
      animation: CaptionAnimation.popIn,
      textColor: Colors.white,
      highlightColor: Color(0xFFCCFF00),
      strokeColor: Colors.black,
      fontWeight: FontWeight.w900,
    ),
    CaptionTemplate(
      id: 'sunset_pop',
      name: 'Sunset Pop',
      animation: CaptionAnimation.popIn,
      textColor: Colors.white,
      highlightColor: Color(0xFFFF7043),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'ice_pop',
      name: 'Ice Pop',
      animation: CaptionAnimation.popIn,
      textColor: Color(0xFF01579B),
      highlightColor: Color(0xFF00E5FF),
      backgroundColor: Color(0xE6FFFFFF),
      strokeWidth: 0,
      fontWeight: FontWeight.w800,
    ),

    // ---------- Bounce style ----------
    CaptionTemplate(
      id: 'neon_bounce',
      name: 'Neon Bounce',
      animation: CaptionAnimation.bounce,
      textColor: Colors.white,
      highlightColor: Color(0xFF39FF14),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'gold_bounce',
      name: 'Gold Bounce',
      animation: CaptionAnimation.bounce,
      textColor: Colors.white,
      highlightColor: Color(0xFFFFD700),
      strokeColor: Colors.black,
      fontWeight: FontWeight.w900,
    ),
    CaptionTemplate(
      id: 'coral_bounce',
      name: 'Coral Bounce',
      animation: CaptionAnimation.bounce,
      textColor: Colors.white,
      highlightColor: Color(0xFFFF6F61),
      strokeColor: Colors.black,
    ),
    CaptionTemplate(
      id: 'violet_bounce',
      name: 'Violet Bounce',
      animation: CaptionAnimation.bounce,
      textColor: Colors.white,
      highlightColor: Color(0xFF9C27B0),
      strokeColor: Colors.black,
      fontWeight: FontWeight.w800,
    ),
    CaptionTemplate(
      id: 'cyan_bounce',
      name: 'Cyan Bounce',
      animation: CaptionAnimation.bounce,
      textColor: Colors.white,
      highlightColor: Color(0xFF18FFFF),
      strokeColor: Colors.black,
    ),

    // ---------- Typewriter style ----------
    CaptionTemplate(
      id: 'typewriter_clean',
      name: 'Typewriter',
      animation: CaptionAnimation.typewriter,
      textColor: Colors.white,
      highlightColor: Colors.white,
      backgroundColor: Color(0xCC000000),
      fontWeight: FontWeight.w600,
    ),
    CaptionTemplate(
      id: 'typewriter_amber',
      name: 'Retro Amber',
      animation: CaptionAnimation.typewriter,
      textColor: Color(0xFFFFB300),
      highlightColor: Color(0xFFFFB300),
      backgroundColor: Color(0xE6000000),
      fontFamily: 'monospace',
    ),
    CaptionTemplate(
      id: 'typewriter_green_console',
      name: 'Terminal Green',
      animation: CaptionAnimation.typewriter,
      textColor: Color(0xFF00FF41),
      highlightColor: Color(0xFF00FF41),
      backgroundColor: Color(0xF0000000),
      fontFamily: 'monospace',
      strokeWidth: 0,
    ),

    // ---------- Slide-up style ----------
    CaptionTemplate(
      id: 'slide_minimal',
      name: 'Slide Minimal',
      animation: CaptionAnimation.slideUp,
      textColor: Colors.white,
      highlightColor: Colors.white,
      backgroundColor: Color(0x99000000),
      fontWeight: FontWeight.w500,
    ),
    CaptionTemplate(
      id: 'slide_rose',
      name: 'Rose Slide',
      animation: CaptionAnimation.slideUp,
      textColor: Colors.white,
      highlightColor: Color(0xFFF06292),
      backgroundColor: Color(0x99AD1457),
    ),
    CaptionTemplate(
      id: 'slide_navy',
      name: 'Navy Slide',
      animation: CaptionAnimation.slideUp,
      textColor: Colors.white,
      highlightColor: Color(0xFF90CAF9),
      backgroundColor: Color(0x991A237E),
    ),

    // ---------- Fade-word style ----------
    CaptionTemplate(
      id: 'pastel_box',
      name: 'Pastel Box',
      animation: CaptionAnimation.fadeWord,
      textColor: Color(0xFF2D2D2D),
      highlightColor: Color(0xFFFF6F91),
      backgroundColor: Color(0xFFFFF3E0),
      strokeWidth: 0,
    ),
    CaptionTemplate(
      id: 'subtle_fade',
      name: 'Subtle Fade',
      animation: CaptionAnimation.fadeWord,
      textColor: Colors.white,
      highlightColor: Colors.white,
      strokeColor: Colors.black45,
      fontWeight: FontWeight.w400,
      fontSize: 0.9,
    ),
    CaptionTemplate(
      id: 'lavender_fade',
      name: 'Lavender Fade',
      animation: CaptionAnimation.fadeWord,
      textColor: Color(0xFF4A148C),
      highlightColor: Color(0xFF7C4DFF),
      backgroundColor: Color(0xFFEDE7F6),
      strokeWidth: 0,
    ),
    CaptionTemplate(
      id: 'peach_fade',
      name: 'Peach Fade',
      animation: CaptionAnimation.fadeWord,
      textColor: Color(0xFF5D4037),
      highlightColor: Color(0xFFFF8A65),
      backgroundColor: Color(0xFFFFF0E6),
      strokeWidth: 0,
    ),

    // ---------- Static / no-animation styles ----------
    CaptionTemplate(
      id: 'top_bar_static',
      name: 'Top Static',
      animation: CaptionAnimation.none,
      textColor: Colors.white,
      highlightColor: Colors.white,
      backgroundColor: Color(0xB3000000),
      position: Alignment.topCenter,
    ),
    CaptionTemplate(
      id: 'center_static',
      name: 'Center Static',
      animation: CaptionAnimation.none,
      textColor: Colors.white,
      highlightColor: Colors.white,
      backgroundColor: Color(0x99000000),
      position: Alignment.center,
      fontWeight: FontWeight.w700,
    ),
    CaptionTemplate(
      id: 'news_ticker',
      name: 'News Ticker',
      animation: CaptionAnimation.none,
      textColor: Colors.white,
      highlightColor: Colors.white,
      backgroundColor: Color(0xFFD32F2F),
      position: Alignment.bottomCenter,
      fontWeight: FontWeight.w700,
      strokeWidth: 0,
    ),
    CaptionTemplate(
      id: 'clean_white_box',
      name: 'Clean White Box',
      animation: CaptionAnimation.none,
      textColor: Color(0xFF212121),
      highlightColor: Color(0xFF212121),
      backgroundColor: Color(0xF2FFFFFF),
      strokeWidth: 0,
      fontWeight: FontWeight.w600,
    ),
  ];

  static CaptionTemplate byId(String id) =>
      all.firstWhere((t) => t.id == id, orElse: () => all.first);
}
